### ISSUE TITLE
pyblish-base dependency instead of pyblish

### ISSUE THREAD

**Issue by Olaf-Wolf3D** [hannesdelbeke/pyblish-plugin-manager#4]
Hey Hannes! When using this as a dependency in a project, it installs the [pyblish](https://github.com/pyblish/pyblish) package, but I don't need the [extras](https://github.com/pyblish/pyblish/blob/9af2db709b4924d58680be13e8fc2ade7161e23f/setup.py#L38-L42) that the pyblish package comes with. The [pyblish-base](https://github.com/pyblish/pyblish-base) package is enough for me.

Can you make the [pyblish](https://github.com/pyblish/pyblish) bundled package an optional dependency, and instead depend on [pyblish-base](https://github.com/pyblish/pyblish-base) only by default?

**Comment by hannesdelbeke** [comment]
updated the requirements, thanks for posting the issue!
